global:
  DATA_PATH: '../dataset/VisDrone2020-CC'
  SIZE: !!python/tuple [540, 960]
  DATA_TEST:
    TRAIN: False
    GT_TRANSFORM: False
prepare:
  GAMMA: 3
  FILENAME_LEN: 5
train:
  TRAIN_BATCH_SIZE: 4
  VAL_BATCH_SIZE: 6
  TEST_BATCH_SIZE: 6
  N_WORKERS: 2
  DEVICE: 'cuda'  # cpu or cuda

  # Path of checkpoint or None
  PRE_TRAINED: '../exp/05-27_18-12_VisDrone_MobileCount_0.0001__1080x1920/all_ep_16_mae_9.8_rmse_12.8.pth'

  # path settings
  EXP_PATH: '../exp'
  DATASET: 'VisDrone'
  NET: 'MobileCount'
  DETAILS: '_1080x1920_NVS'

  # learning optimizer settings
  LR: 1e-4  # learning rate
  W_DECAY: 1e-4  # weight decay
  LR_DECAY: 0.995  # decay rate
  LR_DECAY_START: 0  # when training epoch is more than it, the learning rate will be begin to decay
  NUM_EPOCH_LR_DECAY: 1  # decay frequency
  MAX_EPOCH: 500

  MOMENTUM: 0.95 # Used in SGD

  OPTIM: 'Adam' # Chosen optimizer

  PATIENCE: 20
  EARLY_STOP_DELTA: 1e-2

  PRINT_FREQ: 10

  # ------------------------------VAL------------------------------
  VAL_SIZE: 0.2
  VAL_DENSE_START: 1
  VAL_FREQ: 10  # Before __C.VAL_DENSE_START epoches, the freq is set as __C.VAL_FREQ
#>>>>>>> 1d4f93e507d32de37c0ab3ba81c2c52daeff42f2

#------------------------TEST-----------------------------------------
evaluate:
  BATCH_SIZE: 6
  N_WORKERS: 4
  LOSSES: [ 'rmse', 'mae' ]
  DEVICE: cpu
  OUT_PREDICTIONS: None
model:
  PRETRAINED: '../exp/05-27_18-12_VisDrone_MobileCount_0.0001__1080x1920/all_ep_16_mae_9.8_rmse_12.8.pth'
  GPU: [0]
  NET: 'MobileCount'